# Site settings
title: Craigkj - Dev Scripture
email:
description: TBD
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://craigkj.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  craigkj
# Build settings
markdown: kramdown
